version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PG_DATA: /var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - testtask
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}"     

  postgres.ui:
    image: sosedoff/pgweb
    restart: on-failure
    depends_on:
      - postgres
    links:
      - postgres
    env_file: .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB_NAME}?sslmode=disable
    ports: 
      - 8081:8081
    networks:
      - testtask
    healthcheck:
      test: ["CMD", "nc", "-vz", "127.0.0.1", "8081"] # netcat is pushed but not published yet =( 
      interval: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}"     

  testapi:
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/usr/src/app
    build:
      context: .
      target: development
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB_NAME}
      PORT: ${PORT:-3000}
    command: wait-for-it postgres:5432 -s -t 60 -- yarn start:dev
    ports:
      - 80:${PORT:-3000}
    depends_on:
      - postgres
    healthcheck:
      test: curl -f http://localhost:${PORT:-3000} || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - testtask
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}"     

networks:
  testtask:
